#!/usr/bin/env node
/**
 * 从固定版本的 jsDelivr CDN 下载完整 Lucide sprite，并生成零依赖运行时数据。
 *
 * 更新版本时只改 LUCIDE_VERSION，运行：
 *   node generate-icons.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const LUCIDE_VERSION = '0.547.0';
const SPRITE_URL = `https://cdn.jsdelivr.net/npm/lucide-static@${LUCIDE_VERSION}/sprite.svg`;
const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), 'lucide-icons.mjs');

function parseAttributes(source) {
  const attrs = {};
  for (const match of source.matchAll(/([\w-]+)="([^"]*)"/g)) {
    if (['d', 'x', 'y', 'x1', 'y1', 'x2', 'y2', 'cx', 'cy', 'r', 'rx', 'ry', 'width', 'height', 'points'].includes(match[1])) {
      attrs[match[1]] = match[2];
    }
  }
  return attrs;
}

function parseGeometry(svg, name) {
  const elements = [];
  for (const match of svg.matchAll(/<(path|circle|ellipse|line|polyline|polygon|rect)\b([^>]*)\/>/g)) {
    elements.push([match[1], parseAttributes(match[2])]);
  }
  if (!elements.length) throw new Error(`${name}: 没有解析到 SVG 几何元素`);
  return elements;
}

function parseSprite(svg) {
  const icons = {};
  for (const match of svg.matchAll(/<symbol id="([^"]+)">([\s\S]*?)<\/symbol>/g)) {
    icons[match[1]] = parseGeometry(match[2], match[1]);
  }
  if (!Object.keys(icons).length) throw new Error('sprite.svg 中没有解析到任何 symbol');
  return icons;
}

async function main() {
  const response = await fetch(SPRITE_URL);
  if (!response.ok) throw new Error(`下载失败 ${response.status}: ${SPRITE_URL}`);
  const icons = parseSprite(await response.text());
  const entries = Object.entries(icons).sort(([a], [b]) => a.localeCompare(b));
  const iconLines = entries.map(([name, elements]) => (
    `  ${JSON.stringify(name)}: ${JSON.stringify(elements)},`
  )).join('\n');
  const body = `/**\n`
    + ` * Generated by generate-icons.mjs — do not edit manually.\n`
    + ` * Lucide ${LUCIDE_VERSION}, ISC License: https://lucide.dev/license\n`
    + ` */\n\n`
    + `export const LUCIDE_VERSION = '${LUCIDE_VERSION}';\n`
    + `export const LUCIDE_LICENSE = 'ISC';\n`
    + `export const LUCIDE_ICONS = Object.freeze({\n${iconLines}\n});\n`;
  fs.writeFileSync(OUT, body, 'utf8');
  console.log(`✓ Lucide ${LUCIDE_VERSION}: 完整 ${entries.length} icons → ${OUT}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
